FROM python:3.6-alpine

RUN adduser -D rkustas

WORKDIR /home/rkustas

COPY requirements.txt requirements.txt
RUN python -m taskapp taskapp
RUN taskapp/bin/pip install -r requirements.txt
RUN taskapp/bin/pip install gunicorn

COPY app app
COPY app.py config.py boot.sh ./
RUN chmod +x boot.sh

ENV FLASK_APP app.py

RUN chown -R app:app ./
USER rkustas

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]