FROM python:3.6-alpine

RUN adduser -D app

WORKDIR /home/app

COPY requirements.txt requirements.txt
RUN python -m app app
RUN app/bin/pip install -r requirements.txt
RUN app/bin/pip install gunicorn

COPY app app
COPY app.py config.py boot.sh ./
RUN chmod +x boot.sh

ENV FLASK_APP app.py

RUN chown -R app:app ./
USER app

EXPOSE 5000
ENTRYPOINT ["./boot.sh"]