"""Removing

Revision ID: 0b6ed4acba48
Revises: 96fb959c61ab
Create Date: 2020-08-04 09:58:05.964017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b6ed4acba48'
down_revision = '96fb959c61ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_task_read_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_task_read_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
