"""New tasks

Revision ID: 96fb959c61ab
Revises: afb919b6f785
Create Date: 2020-08-04 08:46:39.783474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96fb959c61ab'
down_revision = 'afb919b6f785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_task_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_task_read_time')
    # ### end Alembic commands ###
